[pytest]
markers =
        api: "API"
        ui: "UI"
        e2e: "E2E"
        positive: "Positive"
        negative: "Negative"
        smoke: "Smoke"
        regression: "Regress"

        addopts = -s -v --alluredir=allure-results